### ISSUE TITLE
tasfile.py has a free field for "console" selection

### ISSUE THREAD

**Issue by roboticanomaly** [Zayitskin/TAStm32GUI#11]
This field is well suited to a dropdown menu with only valid values allowed.  The values should be: "nes", "snes", "n64", "gc", and "genesis" .

**Comment by Zayitskin** [comment]
A good idea. Will probably make it in with #7 (since it looks like it will not get validated for a bit).

**Comment by Zayitskin** [comment]
It is in #7 officially now.

**Comment by Zayitskin** [comment]
Merged.
