### ISSUE TITLE
Missing Feature : Console selection in "main.py" GUI

### ISSUE THREAD

**Issue by roboticanomaly** [Zayitskin/TAStm32GUI#12]
The user could select a new console via the "main.py" GUI rather than just use the one specified in the TAS file.

**Comment by Zayitskin** [comment]
Do you mean they should be able to change the console selection in the main.py? Cause that does not seem like a good idea. The format for parsing the movie is based on the console selected, and if the movie format and console selected at tas file creation do not properly match up, the file should be fixed before it even makes it over to main.py.

**Comment by Ownasaurus** [comment]
Oh I see. I was wondering why it looked like you could change most other parameters but not the console.
