### ISSUE TITLE
main.py : "python3 tastm32.py ..." loads the .tas file, not the .r* file

### ISSUE THREAD

**Issue by roboticanomaly** [Zayitskin/TAStm32GUI#13]
tastm32.py expects the run file, not the TAS file.

**Comment by Zayitskin** [comment]
The command display currently show the filename for the tas file instead of the movie name because I never got around to caching it, and ultimately it didn't matter. The command display was mostly for testing that the various options were representing the correct argument.

**Comment by Zayitskin** [comment]
This is technically an inconsistency, not a bug, but for the sake of not making extraneous tags, it is going in as a bug.

**Comment by roboticanomaly** [comment]
Without the device itself I could not test the correctness of the command, but I agree it will be clearer to the user if the displayed filename is consistent.

**Comment by Zayitskin** [comment]
Readout now shows the name of the movie file instead of the name of the run file.
