### ISSUE TITLE
Add CTRL-C support to close window

### ISSUE THREAD

**Issue by Zayitskin** [Zayitskin/TAStm32GUI#15]
Adding a callback that checks for CTRL-C and then properly closes will make the feel of the applications across multiple platforms more homogeneous, and should also be more responsive the the current reaction on *nix systems.

This needs to be applied to both main.py and tasfile.py.

**Comment by Ownasaurus** [comment]
Specifically, it's NON-responsive on *nix systems until the window gets an update

**Comment by Zayitskin** [comment]
Added for main.py using a subprocess. Still needs to be added to tasfile.py.

**Comment by Zayitskin** [comment]
Added to tasfile.py.
