### ISSUE TITLE
Error when running code as provided

### ISSUE THREAD

**Issue by Ownasaurus** [Zayitskin/TAStm32GUI#2]
When running main.py, the following exception is thrown:
`Traceback (most recent call last):
  File "./main.py", line 433, in <module>
    app = App()
  File "./main.py", line 84, in __init__
    self.run = tk.StringVar(self, self.runs[0]) #TODO: Makes this not crash with no runs
IndexError: list index out of range
`

The #TODO says it all. You might consider catching the exception and exiting gracefully... or perhaps bounds checking. Keep up the great work!

**Comment by Zayitskin** [comment]
Fixed in recent push. Now if no runs exist it says "No runs found" instead of crashing.
