### ISSUE TITLE
Suggestions: Expand the README

### ISSUE THREAD

**Issue by Ownasaurus** [Zayitskin/TAStm32GUI#3]
I think indicating the entry point (main.py) and necessity of installing python-tk in the README would be extremely helpful. Perhaps even instructions for installing python-tk on the various operating systems.

**Comment by Zayitskin** [comment]
Is on the docket, but is currently low priority until all of the necessary features have been implemented. python-tk should also be added to the requirements.txt file, though the usefulness of it being there is currently unknown due to the weird way that tkinter is acquired.

**Comment by Zayitskin** [comment]
I have updated the readme to contain a basic level of information on the python files that are meant to be executed. While the readme is by no means complete, I believe it is sufficient for this issue to be closed, as it is no longer egregiously out of date.
