### ISSUE TITLE
Suggestion: Expand the transition label abbreviations

### ISSUE THREAD

**Issue by Ownasaurus** [Zayitskin/TAStm32GUI#4]
Right now the transitions are labeled as A, N, S, and H. While these are how they work at a low level, by sending those character bytes, the user would benefit from having a more human-readable label. These would be "ACE mode," "Normal mode," "Soft reset," and "Hard reset."

**Comment by Zayitskin** [comment]
Will do. I did not know what they mean, and when I asked, the question got buried before I got an answer.

**Comment by Zayitskin** [comment]
The TransitionsTable now uses the full transition names for transition selection. It still uses the short forms behind the scenes for storage and sending data to the TAStm32.
